# This code was generated by the DeepSeek AI model (;
import math
from django.conf import settings


class PackageCalculator:
    """
    Calculate physical shipment attributes from order items.

    total_weight       — sum of (item weight × qty) across all lines (grams)
    volumetric_weight  — total_volume(mm³) / DIM_FACTOR → kg → grams
    chargeable_weight  — max(total_weight, volumetric_weight)
    package_length     — largest length among items (mm)
    package_width      — largest width among items (mm)
    package_height     — ceil(total_volume / (length × width)) (mm)

    """

    DIM_FACTOR = getattr(settings, 'SHIPPING_DIM_FACTOR', 6000)

    def calculate(self, order_items) -> dict:
        total_weight = 0
        total_volume = 0
        max_length = 0
        max_width = 0

        for item in order_items:
            # Try snapshot first, fall back to live stockrecord
            snapshot = item.stockrecord_snapshot

            if snapshot:
                weight = snapshot.get('weight', 0)
                length = snapshot.get('length', 0)
                width = snapshot.get('width', 0)
                height = snapshot.get('height', 0)
            elif item.stockrecord and item.stockrecord.product_variant:
                variant = item.stockrecord.product_variant
                weight = variant.weight
                length = variant.length
                width = variant.width
                height = variant.height
            else:
                continue  # no data available — skip this item

            qty = item.quantity
            total_weight += weight * qty
            total_volume += (length * width * height) * qty

            if length > max_length:
                max_length = length
            if width > max_width:
                max_width = width

        # Guard against zero dimensions
        max_length = max(max_length, 1)
        max_width = max(max_width, 1)

        base_footprint = max_length * max_width
        max_height = max(math.ceil(total_volume / base_footprint), 1) if base_footprint else 1

        # Volumetric weight: mm³ → kg → grams
        vol_weight_grams = int((total_volume / self.DIM_FACTOR) * 1000) if self.DIM_FACTOR else 0
        chargeable_weight = max(total_weight, vol_weight_grams)

        return {
            'total_weight': total_weight,
            'volumetric_weight': vol_weight_grams,
            'chargeable_weight': chargeable_weight,
            'length': max_length,
            'width': max_width,
            'height': max_height,
        }